### Get Users
GET http://localhost:4004/test/Users

### Post User
POST http://localhost:4004/test/Users
Content-Type: application/json

{"username": "Hello_User", "firstname": "Mac", "lastname": "Intosh", "title": "Apple Developer", "admin": false}

### Get Projects
GET http://localhost:4004/test/Projects


### Post a project
POST http://localhost:4004/test/Projects
Content-Type: application/json

{"projectname": "Test project", "startdate": "2021-04-27", "enddate": "2021-04-30"}


### Get WorkHours
GET  http://localhost:4004/test/WorkHours

### Post WorkHours
POST http://localhost:4004/test/WorkHours
Content-Type: application/json

{"users_username": "User2", "project_ID": "20466921-7d57-4e76-b14c-e53fd97dcb11", "day": "2023-02-21", "starttime": "08:01:23", "endtime": "16:02:43"}